version: "11"
services:
  api:
    build: .
    ports: 
     - 8000:8000 
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fastapi
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

  

